#include "draw.h"
#include "gba.h"

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

#include "images/cover.h"
#include "images/endScreen.h"
#include "images/bird.h"
#include "images/lime.h"
#include "images/userIcon.h"


static void unDrawPlayer(AppState *state) {
    drawRectDMA((state->player).col, (state->player).row, 20, 20, GREEN);
}

static void unDrawdoNotAvoid(AppState *state) {
    drawRectDMA((state->doNotAvoid).col, (state->doNotAvoid).row, 20, 20, GREEN);
}

static void unDrawAvoid(AppState *state) {
    for (int i = 0; i < 4; i++) {
        drawRectDMA(((state->avoid)[i]).col, ((state->avoid)[i]).row, 20, 20, GREEN);
    }
}


// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    fillScreenDMA(GREEN);
    drawString(5, 5, "SCORE: ", BLACK);
    UNUSED(state);

}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    if ((state->doNotAvoid).toDraw == 0) {
        unDrawdoNotAvoid(state);
    }
    unDrawPlayer(state);
    unDrawAvoid(state);
    char reportScore[1];
    sprintf(reportScore, "%i", (state->score));
    drawString(45, 5, reportScore, GREEN);
    // TA-TODO: IMPLEMENT.
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    if ((state->doNotAvoid).toDraw == 1) {
        drawImageDMA((state->doNotAvoid).row, (state->doNotAvoid).col, 20, 20, bird);
    }
    drawImageDMA((state->player).row, (state->player).col, 20, 20, userIcon);
    for (int i = 0; i < 4; i++) {
        drawImageDMA(((state->avoid)[i]).row, ((state->avoid)[i]).col, 20, 20, lime);
    }
    char reportScore[1];
    sprintf(reportScore, "%i", (state->score));
    drawString(45, 5, reportScore, BLACK);
    drawString(37, 144, "Hit the bird, avoid the lime!", BLACK);

}
